### ISSUE TITLE
Processing tradeups takes very long

### ISSUE THREAD

**Issue by Aardappelmoeheid** [daltavida/Uptrade#1]
Hey,

I've been running Uptrade for the last 2 days, and it has not finished yet. Would it be possible to increase the speed of the computation by using np instead of math?

Cheers,

**Comment by daltavida** [comment]
@Aardappelmoeheid Sorry, I didn't think anyone was using this so I didn't provide any instructions haha. 

There are billions of possible combinations so the tradeups are supposed to keep processing basically forever. However, after every 10000 tradeups, the script updates a pickle file with the best tradeups found so far.  So the longer you run the script, the better tradeups you find. 

Once you've run it for a decent amount of time (usually few hours, or whatever you're happy with), you can run the export_excel script and it will create an excel file from the data in pickle files.

**Comment by Aardappelmoeheid** [comment]
@daltavida Thanks so much for your swift reply! I've been trying do do something similar but did not manage an efficient way of extracting prices untill I found this. 

It really shows you know what your doing!

Thanks again and have a nice Christmas

**Comment by daltavida** [comment]
@Aardappelmoeheid  Thank you! I haven't updated the repo since last year so the tradeups might not be accurate. Please check the odds on a tradeup calculator like [csgofloat](https://csgofloat.com/trade-up) before you do any tradeups. 

Also, feel free to reach out to me on daltavida@gmail.com if you need any help. Merry Christmas!
